# Generated by Django 4.2.7 on 2025-10-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1024)),
                ("branch_name", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit Session",
                "verbose_name_plural": "Edit Sessions",
                "ordering": ["-last_modified"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="editor_edit_user_id_476511_idx",
                    ),
                    models.Index(
                        fields=["-last_modified"], name="editor_edit_last_mo_f3eb5c_idx"
                    ),
                ],
            },
        ),
    ]
