# Generated by Django 4.2.7 on 2025-10-25 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="GitOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create_branch", "Create Branch"),
                            ("commit", "Commit"),
                            ("merge", "Merge"),
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("delete_branch", "Delete Branch"),
                            ("static_gen", "Static Generation"),
                            ("conflict_detect", "Conflict Detection"),
                            ("conflict_resolve", "Conflict Resolution"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("file_path", models.CharField(blank=True, max_length=1024)),
                ("request_parameters", models.JSONField(default=dict)),
                ("response_code", models.IntegerField(default=200)),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("git_output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_ms", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Git Operation",
                "verbose_name_plural": "Git Operations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "operation_type"],
                        name="git_service_timesta_c9bd3d_idx",
                    ),
                    models.Index(
                        fields=["success", "-timestamp"],
                        name="git_service_success_f0a859_idx",
                    ),
                ],
            },
        ),
    ]
