name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for git operations

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Git for tests
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "Test User"
        git config --global init.defaultBranch main

    - name: Initialize test wiki repository
      run: |
        mkdir -p repo
        cd repo
        git init
        git config user.email "test@example.com"
        git config user.name "Test User"
        echo "# Test Wiki" > README.md
        git add README.md
        git commit -m "Initial commit"

    - name: Create test environment file
      run: |
        cat > .env << EOF
        SECRET_KEY=test-secret-key-for-ci-only-not-for-production
        DEBUG=True
        DATABASE_URL=sqlite:///db.sqlite3
        REDIS_URL=redis://localhost:6379/0
        ALLOWED_HOSTS=localhost,127.0.0.1
        EOF

    - name: Set up Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '7.x'

    - name: Run migrations
      run: |
        python manage.py migrate --noinput

    - name: Run tests with pytest
      run: |
        pytest --cov=config --cov=git_service --cov=editor --cov=display --cov-report=xml --cov-report=term-missing
      env:
        DJANGO_SETTINGS_MODULE: config.settings

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true
